---
name: UNIVERSAL-can
version: 1.16
author:
  - 'chromatic <chromatic@wgz.org>'
abstract: Hack around people calling UNIVERSAL::can() as a function
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Simple: 0.60
requires:
  Scalar::Util: ''
  Test::Simple: 0.60
  perl: v5.6.2
configure_requires:
  Module::Build: 0.35
provides:
  UNIVERSAL::can:
    file: lib/UNIVERSAL/can.pm
    version: 1.16
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
