---
name: UNIVERSAL-can
version: 1.03
author:
  - chromatic <chromatic@wgz.org>
abstract: Hack around people calling UNIVERSAL::can() as a function
license: perl
requires:
  Scalar::Util: ''
  perl: 5.6.0
build_requires:
  Test::Simple: 0.60
  Test::Warn: 0.08
provides:
  UNIVERSAL::can:
    file: lib/UNIVERSAL/can.pm
    version: 1.03
generated_by: Module::Build version 0.2611
